language: go
env:
  - OS=darwin ARCH=amd64
  - OS=dragonfly ARCH=amd64
  - OS=freebsd ARCH=386
  - OS=freebsd ARCH=amd64
  - OS=freebsd ARCH=arm
  - OS=linux ARCH=386
  - OS=linux ARCH=amd64
  - OS=linux ARCH=arm
  - OS=linux ARCH=arm64
  - OS=netbsd ARCH=386
  - OS=netbsd ARCH=amd64
  - OS=netbsd ARCH=arm
  - OS=openbsd ARCH=386
  - OS=openbsd ARCH=amd64
  - OS=openbsd ARCH=arm
  - OS=solaris ARCH=amd64
  - OS=windows ARCH=386
  - OS=windows ARCH=amd64
matrix:
  allow_failures:
    - env: OS=freebsd ARCH=arm
    - env: OS=openbsd ARCH=386
    - env: OS=openbsd ARCH=amd64
    - env: OS=openbsd ARCH=arm
    - env: OS=windows ARCH=386
    - env: OS=windows ARCH=amd64
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  # workaround for travis-ci/gimme#42
  - export GOOS="${OS}"
  - export GOARCH="${ARCH}"
script:
  - go build -o nixbench-${OS}-${ARCH}
  - if [ ${OS} = "linux" ] && [ ${ARCH} = "amd64" ]; then ./nixbench-linux-amd64; fi
deploy:
  provider: releases
  api_key:
    secure: cSvDAS3E+H3kNbv2hA4ZYnUK4VtAmMN2wCurEmadFEKwXuF3DueyMFfbvONhj82Ykz3/ZK6XGWEXDGDSVePMpfqQJMgsCLu3Llm89WwDl2A5rleeldNLOgTtx6iUteetHrGoj0Hs418QANZ7/AqjoqCvL6xMN/rjoKUTQjF0VMBKIUBPGbZJOhnQZtSvSoQvzcEsmQf/8AqwOHCVzt7kBsuZUsWhxP0NM81Ucz2et8isJ7ufJVzgd836V2qevC5mZLlbf+ZJ1j1loF+HIr1CYQkAELFWGjPfTF0644Jo5x+/9YpBxyzuu9g6YYvW/lnaO/rkTn1thj5ti+fs0cOUW4rwZMQ2nUTDVpfeWraptJ2q6w1i+mPH2at1g9XIu9fka+3eO/o2LSuka70b5gwBOPCyln5lbwuwKEDQF3zvjb7tfuGvzsSVCWYwDstIYcYq/nqTGCD1tXApIDE5pp9zWVYS9+6xJuEd9+TixXSSokSd5Bl8sPhdtJcEdOToePQvySmtEHR7IDjhSoRTCshTJe35r2E2iurUmOEFNXDJQjBXgzgLZquqCS48wWS6xVdc50MFB5VFyznjRwOAj8J3MEWAdB4d/JNGbCsuZnH6G6xxteEyPsjMC6bvHWI3cxG+4i8c3o3wJG59pPQv59nmo917jdInXBOUVrUEbrJAlWs=
  file: nixbench-${OS}-${ARCH}
  skip_cleanup: true
  on:
    tags: true
